apiVersion: v1
kind: PersistentVolume
metadata:
  name: pihole-pihole-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: pihole-storage
  local:
    path: /mnt/pihole/pihole
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: disk
            operator: In
            values:
            - disk1  
