apiVersion: v1
kind: PersistentVolume
metadata:
  name: pihole-dnsmasq-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: pihole-storage
  local:
    path: /mnt/pihole/dnsmasq.d
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: disk
            operator: In
            values:
            - disk1  
